name: Build Windows App
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm install
      - name: Build Web App
        run: npm run build
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build Tauri App
        run: npx tauri build
      - name: Upload Windows MSI
        uses: actions/upload-artifact@v4
        with:
          name: AceMock-Windows-Installer
          path: src-tauri/target/release/bundle/msi/*.msi
